export const TOKENS = {
    Logger: 'Logger',
    Config: 'Config',
    Database: 'Database',
    Messaging: 'Messaging',
    Cache: 'Cache',
    AuthService: 'AuthService',
    UserService: 'UserService',
    RepositoryFactory: 'RepositoryFactory',
    ServiceFactory: 'ServiceFactory',
    AuthControllerFactory: 'AuthControllerFactory',
    UserControllerFactory: 'UserControllerFactory',
    WorkspaceRepository: 'WorkspaceRepository',
    WorkspaceRoleRepository: 'WorkspaceRoleRepository',
    WorkspaceMembersRepository: 'WorkspaceMembersRepository',
    UserPreferencesRepository: 'UserPreferencesRepository',
    UserPreferencesService: 'UserPreferencesService',
    WorkspaceService: 'WorkspaceService',
    WorkspaceControllerFactory: 'WorkspaceControllerFactory',
    FeatureFlagRepository: 'FeatureFlagRepository',
    FeatureFlagService: 'FeatureFlagService',
    FeatureFlagControllerFactory: 'FeatureFlagControllerFactory',
    WorkspaceRolesControllerFactory: 'WorkspaceRolesControllerFactory',
    SubscriptionPlanRepository: 'SubscriptionPlanRepository',
    UserSubscriptionRepository: 'UserSubscriptionRepository',
    SubscriptionService: 'SubscriptionService',
    // Account domain
    AccountRepository: 'AccountRepository',
    AccountService: 'AccountService',
    AccountController: 'AccountController',
};
