export const TOKENS = {
    Logger: 'Logger',
    Config: 'Config',
    Database: 'Database',
    Messaging: 'Messaging',
    Cache: 'Cache',
    AuthService: 'AuthService',
    UserService: 'UserService',
    RepositoryFactory: 'RepositoryFactory',
    ServiceFactory: 'ServiceFactory',
    AuthControllerFactory: 'AuthControllerFactory',
    UserControllerFactory: 'UserControllerFactory',
    WorkspaceRepository: 'WorkspaceRepository',
    WorkspaceRoleRepository: 'WorkspaceRoleRepository',
    WorkspaceMembersRepository: 'WorkspaceMembersRepository',
    WorkspaceInvitationsRepository: 'WorkspaceInvitationsRepository',
    UserPreferencesRepository: 'UserPreferencesRepository',
    UserPreferencesService: 'UserPreferencesService',
    WorkspaceService: 'WorkspaceService',
    WorkspaceControllerFactory: 'WorkspaceControllerFactory',
    FeatureFlagRepository: 'FeatureFlagRepository',
    FeatureFlagService: 'FeatureFlagService',
    FeatureFlagControllerFactory: 'FeatureFlagControllerFactory',
    WorkspaceRolesControllerFactory: 'WorkspaceRolesControllerFactory',
    SubscriptionPlanRepository: 'SubscriptionPlanRepository',
    UserSubscriptionRepository: 'UserSubscriptionRepository',
    SubscriptionService: 'SubscriptionService',
    // Account domain
    AccountRepository: 'AccountRepository',
    AccountService: 'AccountService',
    AccountController: 'AccountController',
    AccountControllerFactory: 'AccountControllerFactory',
    // Transaction domain
    TransactionRepository: 'TransactionRepository',
    TransactionService: 'TransactionService',
    TransactionController: 'TransactionController',
    TransactionControllerFactory: 'TransactionControllerFactory',
    // Exchange rate domain
    ExchangeRateRepository: 'ExchangeRateRepository',
    ExchangeRateService: 'ExchangeRateService',
    ExchangeRateControllerFactory: 'ExchangeRateControllerFactory',
    // Category domain
    CategoryRepository: 'CategoryRepository',
    CategoryService: 'CategoryService',
    CategoryControllerFactory: 'CategoryControllerFactory',
    // Analytics domain
    AnalyticsService: 'AnalyticsService',
    AnalyticsController: 'AnalyticsController',
    AnalyticsControllerFactory: 'AnalyticsControllerFactory',
    // Storage domain
    StorageRepository: 'StorageRepository',
    StorageService: 'StorageService',
    StorageController: 'StorageController',
    StorageServiceFactory: 'StorageServiceFactory',
    StorageControllerFactory: 'StorageControllerFactory',
    // Payment domain
    PaymentRepository: 'PaymentRepository',
    PaymentService: 'PaymentService',
    PaymentControllerFactory: 'PaymentControllerFactory',
    // User domain
    UserRepository: 'UserRepository',
    // Additional controller factories
    SubscriptionControllerFactory: 'SubscriptionControllerFactory',
    ReportControllerFactory: 'ReportControllerFactory',
    SettingsControllerFactory: 'SettingsControllerFactory',
};
