export const TOKENS = {
    Logger: 'Logger',
    Config: 'Config',
    Database: 'Database',
    Messaging: 'Messaging',
    Cache: 'Cache',
    AuthService: 'AuthService',
    UserService: 'UserService',
    RepositoryFactory: 'RepositoryFactory',
    ServiceFactory: 'ServiceFactory',
    AuthControllerFactory: 'AuthControllerFactory',
    UserControllerFactory: 'UserControllerFactory',
    OrganizationRepository: 'OrganizationRepository',
    OrganizationRoleRepository: 'OrganizationRoleRepository',
    OrganizationMembersRepository: 'OrganizationMembersRepository',
    UserPreferencesRepository: 'UserPreferencesRepository',
    UserPreferencesService: 'UserPreferencesService',
    OrganizationService: 'OrganizationService',
    OrganizationControllerFactory: 'OrganizationControllerFactory',
    FeatureFlagRepository: 'FeatureFlagRepository',
    FeatureFlagService: 'FeatureFlagService',
    FeatureFlagControllerFactory: 'FeatureFlagControllerFactory',
    OrganizationRolesControllerFactory: 'OrganizationRolesControllerFactory',
    SubscriptionPlanRepository: 'SubscriptionPlanRepository',
    OrganizationSubscriptionRepository: 'OrganizationSubscriptionRepository',
    SubscriptionService: 'SubscriptionService',
};
